version: '3'

services:

#Redis
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    restart: always
    entrypoint: redis-server --appendonly yes

# SentenceDiagramming API service
  sd_api:
    build: .
    env_file:
    - .env
    ports:
      - 8080:8080
